export const COMPONENTS_LOAD_PAGE = 'COMPONENTS_LOAD_PAGE';
export const COMPONENTS_LOADING = 'COMPONENTS_LOADING';
export const COMPONENTS_LOADING_ERROR = 'COMPONENTS_LOADING_ERROR';

export const COMPONENT_DELETE = 'COMPONENT_DELETE';

export const COMPONENTFORM_SUBMIT = 'COMPONENTFORM_SUBMIT';

export const CRUDFORM_SUBMIT = 'CRUDFORM_SUBMIT';

export const CRUDLIST_ACTION_EDIT = 'CRUDLIST_ACTION_EDIT';
export const CRUDLIST_ACTION_DELETE = 'CRUDLIST_ACTION_DELETE';
export const CRUDLIST_PAGINATION_CHANGE = 'CRUDLIST_PAGINATION_CHANGE';

export const LOGIN_START = 'LOGIN_START';

export const SECURITY_REFRESH = 'SECURITY_REFRESH';

export const UPLOAD_START = 'UPLOAD_START';
